---
title: "Erson_Analysis_Internal_Samples"
output: html_document
date: "2025-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Sample 1

#### Initial QC

```{r, eval = FALSE}
CreateSeuratObject("~/Documents/Erson_Lab/Datasets/Erson Samples/PA_SC_SR/DATA1/DATA1.H5",
                   "sample1", 
                   "sample1")
sample1 <- AddMitoRna(sample1)
MakeVlnPlot(sample1)
sample1 <- QCSeurat(sample1, 200, 3000, 25)
FeatureScatter(sample1, "nCount_RNA", "percent.mt")
FeatureScatter(sample1, "nCount_RNA", "nFeature_RNA")
sample1 <- NormalizeAndVariable(sample1)
sample1 <- Scale(sample1)
sample1 <- PcaElbow(sample1)
MakeHeatmap(sample1, 1:8)
```

#### General Exploratory Analyses

```{r, eval = FALSE}
sample1 <- FindCellClusters(sample1, 1:7, 0.5)
sample1 <- RunUMAP(sample1, dims = 1:7)
sample1 <- FindPosMarkers(sample1)
sample1 <- SingleHPCA(sample1)
sample1 <- SingleNeuro(sample1)
sample1 <- SingleImmune(sample1)
```

#### Specific Exploratory Analysis/Visualizations

```{r, eval = FALSE}
#For immune characterization
    SeuratFiltered <- subset(sample1, subset = NeuroCellLabels == "Imm")
    CategoryCounts <- SeuratFiltered@meta.data %>%
      group_by(ImmuneCellLabels) %>%
      tally()
    ValidCategories <- CategoryCounts %>% 
      filter(n >= 5) %>%
      pull(ImmuneCellLabels)
    
    MakeUMAP(sample1, 1:7)
    
print(DimPlot(subset(sample1, subset = NeuroCellLabels == "Imm" & ImmuneCellLabels %in% ValidCategories, cols = MyColors), reduction = "umap", group.by = "ImmuneCellLabels", label = FALSE) + ggtitle("Immune Cell Types"))


Idents(sample1) <- sample1@meta.data$NeuroCellLabels
BarPlot(sample1, 8224) + ggtitle("Unbiased Neuroendocrine Cell Type Distribution")
```

### Sample 2

```{r, eval = FALSE}
CreateSeuratObject("~/Documents/Erson_Lab/Datasets/Erson Samples/PA_SC_SR/DATA2/filtered_feature_bc_matrix.h5",
                   "sample2", 
                   "sample2" )
sample2 <- AddMitoRna(sample2)
MakeVlnPlot(sample2)
dim(sample2)
sample2 <- QCSeurat(sample2, 200, 5000, 30)
dim(sample2)
FeatureScatter(sample2, "nCount_RNA", "nFeature_RNA")
sample2 <- NormalizeAndVariable(sample2)
sample2 <- Scale(sample2)
sample2 <- PcaElbow(sample2)
sample2 <- RunUMAP(sample2, dims = 1:9)
sample2 <- FindCellClusters(sample2, 1:9, 0.5)
DimPlot(sample2, reduction = "umap", label = TRUE) 
sample2 <- FindPosMarkers(sample2)
sample2 <- SingleUnbiasedNeuro(sample2)

    #For immune characterization
    SeuratFiltered <- subset(sample2, subset = NeuroCellLabels == "Imm")
    CategoryCounts <- SeuratFiltered@meta.data %>%
      group_by(ImmuneCellLabels) %>%
      tally()
    ValidCategories <- CategoryCounts %>% 
      filter(n >= 5) %>%
      pull(ImmuneCellLabels)

print(DimPlot(subset(sample2, subset = NeuroCellLabels == "Imm" & ImmuneCellLabels %in% ValidCategories), reduction = "umap", group.by = "ImmuneCellLabels") + ggtitle("Sample 2 Immune Cell Types"))
Idents(sample2) <- sample2@meta.data$UnbiasedNeuroCellLabels
BarPlot(sample2, 7359) + ggtitle("Unbiased Neuroendocrine Cell Type Distribution")
```

### Sample 3

```{r, eval = FALSE}
CreateSeuratObject("~/Documents/Erson_Lab/Datasets/Erson Samples/PA_SC_SR/DATA3/filtered_feature_bc_matrix.h5",
                   "sample3", 
                   "sample3")
sample3 <- AddMitoRna(sample3)
MakeVlnPlot(sample3)
dim(sample3)
sample3 <- QCSeurat(sample3, 200, 4000, 40)
dim(sample3)
FeatureScatter(sample3, "nCount_RNA", "percent.mt")
FeatureScatter(sample3, "nCount_RNA", "nFeature_RNA")
sample3 <- NormalizeAndVariable(sample3)
sample3 <- Scale(sample3)
sample3 <- PcaElbow(sample3)
MakeHeatmap(sample3, 1:10)
sample3 <- FindCellClusters(sample3, 1:10, 1)
sample3 <- RunUMAP(sample3, dims = 1:10)
DimPlot(sample3, reduction = "umap", label = TRUE, group.by = "UnbiasedNeuroCellLabels")
sample3 <- FindPosMarkers(sample3)
sample3 <- SingleUnbiasedNeuro(sample3)

#For immune characterization
SeuratFiltered <- subset(sample3, subset = NeuroCellLabels == "Imm")
CategoryCounts <- SeuratFiltered@meta.data %>%
  group_by(ImmuneCellLabels) %>%
  tally()
ValidCategories <- CategoryCounts %>% 
  filter(n >= 5) %>%
  pull(ImmuneCellLabels)

print(DimPlot(subset(sample3, subset = NeuroCellLabels == "Imm" & ImmuneCellLabels %in% ValidCategories), reduction = "umap", group.by = "ImmuneCellLabels") + ggtitle("Sample 3 Immune Cell Types"))
Idents(sample3) <- sample3@meta.data$UnbiasedNeuroCellLabels
BarPlot(sample3, 6200) + ggtitle("Unbiased Neuroendocrine Cell Type Distribution")

```

### Sample 4

```{r, eval = FALSE}
CreateSeuratObject("~/Documents/Erson_Lab/Datasets/Erson Samples/PA_SC_SR/DATA4/filtered_feature_bc_matrix.h5",
                   "sample4", 
                   "sample4" )
sample4 <- AddMitoRna(sample4)
MakeVlnPlot(sample4)
dim(sample4)
sample4 <- QCSeurat(sample4, 200, 5000, 7)
dim(sample4)
FeatureScatter(sample4, "nCount_RNA", "percent.mt")
FeatureScatter(sample4, "nCount_RNA", "nFeature_RNA")
sample4 <- NormalizeAndVariable(sample4)
sample4 <- Scale(sample4)
sample4 <- PcaElbow(sample4)
MakeHeatmap(sample4, 1:11)
sample4 <- FindCellClusters(sample4, 1:11, 1)
sample4 <- FindPosMarkers(sample4)
sample4 <- SingleUnbiasedNeuro(sample4)
sample4 <- RunUMAP(sample4, dims = 1:11)
print(DimPlot(sample4, reduction = "umap", group.by = "UnbiasedNeuroCellLabels", label = TRUE) + ggtitle("Unbiased Neuroendocrine Cell Types"))
Idents(sample4) <- sample4@meta.data$UnbiasedNeuroCellLabels
    
    #for immune characterization
    SeuratFiltered <- subset(sample4, subset = NeuroCellLabels == "Imm")
    CategoryCounts <- SeuratFiltered@meta.data %>%
      group_by(ImmuneCellLabels) %>%
      tally()
    ValidCategories <- CategoryCounts %>% 
      filter(n >= 1) %>%
      pull(ImmuneCellLabels)

BarPlot(sample4, 14986) + ggtitle("Unbiased Neuroendocrine Cell Type Distribution")
BarPlot(sample4, 14986)
VlnPlot(sample4, features = "STAT6") +  NoLegend() + ggtitle("STAT6 (P3/CD/Tumor)")
```

### Sample 5

```{r, eval = FALSE}
#Sample 5
CreateSeuratObject("~/Documents/Erson_Lab/Datasets/Erson Samples/PA_SC_SR/DATA5/filtered_feature_bc_matrix.h5",
                   "sample5", 
                   "sample5" )
sample5 <- AddMitoRna(sample5)
MakeVlnPlot(sample5)
dim(sample5)
sample5 <- QCSeurat(sample5, 200, 2000, 40)
dim(sample5)
FeatureScatter(sample5, "nCount_RNA", "percent.mt")
FeatureScatter(sample5, "nCount_RNA", "nFeature_RNA")
sample5 <- NormalizeAndVariable(sample5)
sample5 <- Scale(sample5)
sample5 <- PcaElbow(sample5)
MakeHeatmap(sample5, 1:12)
sample5 <- FindCellClusters(sample5, 1:9, 1.5)
sample5 <- FindPosMarkers(sample5)
sample5 <- SingleUnbiasedNeuro(sample5)
sample5 <- RunUMAP(sample5, dims = 1:9)
print(DimPlot(sample5, reduction = "umap", group.by = "UnbiasedNeuroCellLabels") + ggtitle("Unbiased Neuroendocrine Cell Types"))
Idents(sample5) <- sample5@meta.data$UnbiasedNeuroCellLabels

#for immune characterization
SeuratFiltered <- subset(sample5, subset = NeuroCellLabels == "Imm")
CategoryCounts <- SeuratFiltered@meta.data %>%
  group_by(ImmuneCellLabels) %>%
  tally()
ValidCategories <- CategoryCounts %>% 
  filter(n >= 1) %>%
  pull(ImmuneCellLabels)
BarPlot(sample5, 1638) + ggtitle("Neuroendocrine Cell Distribution")
```

### Sample 6 (Omitted)

### Sample 7

```{r, eval = FALSE}
CreateSeuratObject("~/Documents/Erson_Lab/Datasets/Erson Samples/PA_SC_SR/DATA7/filtered_feature_bc_matrix.h5",
                   "sample7", 
                   "sample7")
sample7 <- AddMitoRna(sample7)
MakeVlnPlot(sample7)
dim(sample7)
sample7 <- QCSeurat(sample7, 200, 2000, 9)
dim(sample7)
FeatureScatter(sample7, "nCount_RNA", "percent.mt")
FeatureScatter(sample7, "nCount_RNA", "nFeature_RNA")
sample7 <- NormalizeAndVariable(sample7)
sample7 <- Scale(sample7)
sample7 <- PcaElbow(sample7)
MakeHeatmap(sample7, 1:12)
sample7 <- FindCellClusters(sample7, 1:9, 1)
sample7 <- FindPosMarkers(sample7) 
sample7 <- SingleUnbiasedNeuro(sample7)
sample7 <- RunUMAP(sample7, dims = 1:9)
print(DimPlot(sample7, reduction = "umap", group.by = "UnbiasedNeuroCellLabels", label = TRUE) + ggtitle("Unbiased Neuroendocrine Cell Types"))
Idents(sample7) <- sample7@meta.data$UnbiasedNeuroCellLabels
BarPlot(sample7, 10370) + ggtitle("Unbiased Neuroendocrine Cell Types")

#for immune characterization
SeuratFiltered <- subset(sample7, subset = NeuroCellLabels == "Imm")
CategoryCounts <- SeuratFiltered@meta.data %>%
    group_by(ImmuneCellLabels) %>%
    tally()
    ValidCategories <- CategoryCounts %>% 
    filter(n >= 1) %>%
    pull(ImmuneCellLabels)
BarPlot(subset(sample7, subset = NeuroCellLabels == "Imm"), 10370) + ggtitle("Immune Cell Distribution")
```
